# Generated by Django 5.0.6 on 2024-06-19 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="member",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="server_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
